name    'kayak-bamboo_agent'
version '0.0.2'
source  'git://github.com/kayakco/puppet-bamboo_agent.git'
author  'kayak'
license 'Apache License, Version 2.0'
summary 'Manages Bamboo agents'
description 'Fine-grained control of Bamboo agents on a node'
project_page 'https://github.com/kayakco/puppet-bamboo_agent'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/java', '>= 0.2.0'
dependency 'kayak/r9util', '>= 0.0.2'
