name    'kayak-bamboo_agent'
version '0.0.7'
source  'git://github.com/kayakco/puppet-bamboo_agent.git'
author  'kayak'
license 'Apache License, Version 2.0'
summary 'Advanced management of Atlassian Bamboo agents'
description 'Installation and fine-grained control of Bamboo agents on a node, including agent capabilities and properties in wrapper.conf'
project_page 'https://github.com/kayakco/puppet-bamboo_agent'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/java', '>= 0.2.0'
dependency 'kayak/r9util', '>= 0.0.3'
